# Generated by Django 3.2.3 on 2021-05-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_id', models.CharField(max_length=10)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.person')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalClimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_type', models.CharField(max_length=40)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.animal')),
            ],
        ),
    ]
