# Generated by Django 3.2.3 on 2021-05-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='last_visited_country',
            field=models.CharField(default='USA', max_length=40),
            preserve_default=False,
        ),
    ]
