# Generated by Django 3.2.3 on 2021-05-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_passport_last_visited_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='passport',
            name='visited_countries',
            field=models.ManyToManyField(to='info.Country'),
        ),
    ]
