# Generated by Django 3.2.3 on 2021-05-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20210526_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country_of_origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='info.country'),
            preserve_default=False,
        ),
    ]
