# Generated by Django 3.2.3 on 2021-05-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_person_country_of_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='last_visited_country',
        ),
    ]
